### PR TITLE
maint: bump deps for 2.4

### PR DESCRIPTION
**Pull request by fchikwekwe**
## Which problem is this PR solving?

Closes #960 
Closes #961 
Closes #962 

## Short description of the changes

Fixing all dependency updates for 2.4 release

### CODE REVIEW

**Comment by fchikwekwe** [comment]
I'm looking into the build failures with the WindowedThroughput test. I think this might a test we've had trouble with in the past. The error message indicates a race condition so I was checking the `sample` package for any areas where we might need to lock data access.

**Comment by kentquirk** [comment]
I just recreated the race condition on my machine. It's probably real. Looking into it now.

**Comment by kentquirk** [comment]
Yup, it's real, and a problem in dynsampler-go. Fix is [here](https://github.com/honeycombio/dynsampler-go/pull/73). 

Once that's merged, we can pull it in as part of this PR.

**Comment by fchikwekwe** [comment]
Oh shoot, I leave for dinner and you've already fixed it! Looking at that PR.

**Comment by kentquirk** [comment]
You'll need to add an update of the dynsampler-go library, which should fix the test.

**Review by kentquirk — APPROVED** [review]
LGTM!

**Pull request merged**
