### PR TITLE
feat: Rename EnableTraceLocality to DisableTraceLocality

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
## Which problem is this PR solving?

To allow users to opt-in safely for disabling trace locality, we're renaming the option to disable trace locality.

## Short description of the changes
- Rename `EnableTraceLocality` to `DisableTraceLocality`

### CODE REVIEW

**Comment by VinozzZ** [comment]
Should we just change the config option to `DisableTraceLocality` and then we will be able to leave the default as `false`?

**Comment by kentquirk** [comment]
I just made a bunch of text edits around this change. Please check them out.

**Review by VinozzZ — COMMENTED** [review]
I made some changes in this PR as well. @MikeGoldsmith do u mind to give a verbal approval and then i can hit the approve button?

**Comment by MikeGoldsmith** [comment]
Thanks @VinozzZ - updates look good

**Review by VinozzZ — APPROVED** [review]

**Pull request merged**
